### ISSUE TITLE
New textures

### ISSUE THREAD

**Issue by XenonCoder** [XenonCoder/TerraCraft#17]
New free textures, directly from my version of "PixelBox", texture pack for Minetest.

![screenshot.png](https://s17.postimg.org/dk7mjg7n3/screenshot.png)

**Comment by benmoran56** [comment]
Link is broken :(

Regarding textures, I have a plan to simplify things. Right now, the block module has a few functions to generate the texture coordinates. We can get rid of that, and just use the pyglet.resource module and image.ImageGrid classes. It will be simpler to add additional textures later. I will make a pull request, so you can see if you like the change.
