### ISSUE TITLE
Reorganization of the code (new modules)

### ISSUE THREAD

**Issue by XenonCoder** [XenonCoder/TerraCraft#18]
The main.py module has become too big! I want to divide the classes and functions into various modules to make the project more organized and easy to manage.

**Comment by XenonCoder** [comment]
Now the project is organized in a better way, it is easier to work comfortably without scrolling over 1000 lines of code in a single module :thumbsup:

**Comment by benmoran56** [comment]
I have actually started a refactoring of the original codebase myself, into an ECS design. You can see my work here:  https://github.com/benmoran56/Minecraft
The "ecs.py" module is a copy of my `esper` ECS library, which is a simple drop in). The codebase is about 70% refactored to an ECS design; the BlockController class still needs to be broken into Processors.

This refactor is also arranged to have the code in one Scene, which will make it easy to seperate the main menu, game field, etc. with a simple SceneManager. 

Would you be open to adopting this type of design for TerraCraft? In my opinion it's the easiest way to go for maintainability and refactoring, which is important for projects that might have many contributors.

**Comment by benmoran56** [comment]
As an update, I have opened a pull request instead.

**Comment by benmoran56** [comment]
As an update, I have opened a smaller pull request. Maybe we can forget about the ECS refactor for now, unless it makes sense to you.

**Comment by XenonCoder** [comment]
Yes, it's a good idea for me. My intention is to implement a main menu, and other features making them separate from the current code (classes and external functions), so your idea is 100% adherent to mine. Thank you for your help, I appreciate it very much.
