### ISSUE TITLE
Need to write a new function to create the vertex points for the block highlight

### ISSUE THREAD

**Issue by benmoran56** [XenonCoder/TerraCraft#30]
The block highlighting is currently a little strange looking, due to changes in my recent pull request. Please assign this to me, and I will fix it when I have some time.

**Comment by XenonCoder** [comment]
Thanks so much.

**Comment by benmoran56** [comment]
As part of this, I will also look into switching over to indexed vertex lists. Currently, there are 24 vertex points for each Block, but most of these are repeated. 

Using indexed vertex lists will save some GPU memory, but it might take longer to create each block in the Scene. We don't really need to worry about GPU memory for this type of game, so switching to indexed vertex lists is only a good idea if it's faster. I'll try to make a small benchmark and see the results.
